#ifndef __DB_H__
    #define __DB_H__

#include <stdint.h>
#include "rcserver.h"

#define _DEBUG_DB_READ


#define _CANT_MAX_EQ    10000
#define _CANT_MAX_HUB   (_CANT_MAX_EQ / 100)
#define _DB_ADDRESS "host=localhost dbname=ltdb user=scallozzo password=italo5056"

//#define _DB_ADDRESS "host=localhost dbname=ltdb user=admin password=italo5056"
//#define _DB_ADDRESS "host=localhost dbname=redcam user=admin password=italo5056"
//#define _DB_ADDRESS "host=localhost dbname=iarnet user=iarnet password=!4rN3T!"

typedef enum
{
    _DB_STS_OK   = 0,
    _DB_STS_ERR_CONN,
    _DB_STS_ERR_ACCESS,
    _DB_STS_ERR_STRUCT,
    _DB_STS_ERR_CMD,
    _DB_STS_ERR_DBLAYOUT,
}eerrmsg;

typedef struct
{
    uint8_t Id;
    uint8_t version[3];
}stDb_T_db_version;
#define _MAXCOLSDBVERSION    2

/*
typedef struct
{
    uint32_t id;
    uint8_t name[64 + sizeof(char)];
    uint8_t folder_name[64 + sizeof(char)];
}stDb_T_municipalities;
#define _MAXCOLSDBMUNICIPALITIES    3
*/

typedef struct
{
    uint32_t id;                            // id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    uint16_t cid;                           // cid int2 NOT NULL,		-- cid = Country ID (54 = ARG)
    uint16_t pid;                           // pid int2 NOT NULL,		-- province id 
    uint32_t sector_id;                     // sector_id int4 NOT NULL,	-- sector id (código único numérico) 
    uint8_t sector_name[30 + sizeof(char)];	// sector_name varchar(30) NOT NULL,
    uint8_t folder_name[30 + sizeof(char)]; // folder_name varchar(30) NOT NULL,
    uint8_t is_public_sector;               // is_public_sector bool NOT NULL,
    uint8_t is_geopos;                      // is_geopos bool NOT NULL,
    uint8_t map_file[32 + sizeof(char)];    // map_file varchar(32) NOT NULL,
}stDb_T_sector;
#define _MAXCOLSDBSECTOR    9


typedef struct
{
    uint32_t id;                                // idx int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    uint8_t eqid[17];                           // eqid char(17) NOT NULL,  	-- Dirección de red (Formato string-hexa 12:34:56:78:9A:BC)
    uint8_t linkid[17];                         // linkid char(17) NOT NULL,  	-- Dirección del master (solo si is_linked = true), (Formato string-hexa 12:34:56:78:9A:BC)
    uint8_t hubid[17];                          // hubid char(17) NOT NULL, 	-- ID de la unidad central repetidora (Formato string-hexa 12:34:56:78:9A:BC)
    uint8_t _iud[20];                           // _uid char(20) NOT NULL,  	-- ID/Nombre local del dispositivo
    uint8_t creation_date[20 + sizeof(char)];   // date_time timestamptz NOT NULL DEFAULT now(), 
    uint16_t devtype;                           // devtype int2 NOT NULL,  	-- Enum del tipo de dispositivo (0-63) Tipo Luminaria, (64-127) Tipo de SIT, (128-255) Sistema de infracciones.
    uint8_t serial_number[32 + sizeof(char)];   // serial_number varchar(32) NOT NULL,
    uint8_t _name[32 + sizeof(char)];           // _name varchar(32) NOT NULL,
    uint8_t model[16 + sizeof(char)];           // model varchar(16) NOT NULL,
    uint8_t address[20 + sizeof(char)];         // address varchar(20) NOT NULL,
    uint8_t address_number[10 + sizeof(char)]; 	// address_number varchar(10) NOT NULL,
    uint8_t intersection[32 + sizeof(char)];    // intersection varchar(32) NOT NULL,
    uint8_t zipcode[16 + sizeof(char)];         // zipcode varchar(16) NOT NULL,
	int32_t mapposx;                            // mapposx int NOT NULL,
	int32_t mapposy;                            // mapposy int NOT NULL,
	float geo_latitude;                         // geo_latitude float NOT NULL,
	float geo_longitude;                        // geo_longitude float NOT NULL,
	uint8_t description[32 + sizeof(char)];     // description varchar(32) NULL,
	uint32_t sector_id;                         // sector_id int4 NOT NULL,	-- Sector id de la tabla "sector" al que corresponde el dispositivo
	uint8_t map_loc[32 + sizeof(char)];         // map_loc char(32) NOT NULL,	-- Localidad / Ciudad
	uint16_t map_pag;                           // map_pag int2 NOT NULL,		-- Página dentro del mapa 
	uint8_t is_enabled;                         // is_enabled bool NOT NULL,
	uint8_t is_linked;                          // is_linked bool NOT NULL,
	uint32_t devconfig;                         // devconfig int NOT NULL,  	-- Configuración para el dispositivo, (bitcode)
}stDb_T_devices;
#define _MAXCOLSDBDEVICES    25


int _Init_dbread(void);
int _dbread_table_tableschema_sector(void);
int _dbread_table_tableschema_dev(void);
int _dbread_table_version(void);
int _dbread_table_muni(void);
int _dbread_table_devices(void); 
int _dbread_bulk(void);
stDb_T_devices *_Stfind_Eqid(uint8_t *peqid, uint8_t eqlen);
//stDb_T_sector *_Stfind_muni(uint32_t mid);
uint8_t *_Findtargetfolder(uint8_t *peqid, uint8_t eqlen);
int8_t _CheckEq(uint8_t *peqid, uint8_t eqlen);
int8_t _CheckHubId(uint8_t *peqid, uint8_t eqlen);









#endif