#ifndef __DB_H__
    #define __DB_H__

#include <stdint.h>
#include "rcserver.h"

#define _DEBUG_DB_READ


#define _CANT_MAX_EQ    10000
#define _CANT_MAX_HUB   (_CANT_MAX_EQ / 100)
#define _DB_ADDRESS "host=localhost dbname=lumina user=postgres password=lumina"

//#define _DB_ADDRESS "host=localhost dbname=ltdb user=scallozzo password=italo5056"
//#define _DB_ADDRESS "host=localhost dbname=ltdb user=admin password=italo5056"
//#define _DB_ADDRESS "host=localhost dbname=redcam user=admin password=italo5056"
//#define _DB_ADDRESS "host=localhost dbname=iarnet user=iarnet password=!4rN3T!"

typedef enum
{
    _DB_STS_OK   = 0,
    _DB_STS_ERR_CONN,
    _DB_STS_ERR_ACCESS,
    _DB_STS_ERR_STRUCT,
    _DB_STS_ERR_CMD,
    _DB_STS_ERR_DBLAYOUT,
}eerrmsg;

/*
typedef struct
{
    uint32_t id;
    uint8_t name[64 + sizeof(char)];
    uint8_t folder_name[64 + sizeof(char)];
}stDb_T_municipalities;
#define _MAXCOLSDBMUNICIPALITIES    3
*/

typedef struct
{
    uint32_t id;                            // id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    uint16_t cid;                           // cid int2 NOT NULL,		-- cid = Country ID (54 = ARG)
    uint16_t pid;                           // pid int2 NOT NULL,		-- province id 
    uint32_t sector_id;                     // sector_id int4 NOT NULL,	-- sector id (código único numérico) 
    uint8_t sector_name[30 + sizeof(char)];	// sector_name varchar(30) NOT NULL,
    uint8_t folder_name[30 + sizeof(char)]; // folder_name varchar(30) NOT NULL,
    uint8_t is_public_sector;               // is_public_sector bool NOT NULL,
    uint8_t is_geopos;                      // is_geopos bool NOT NULL,
    uint8_t map_file[32 + sizeof(char)];    // map_file varchar(32) NOT NULL,
}stDb_T_sector;
#define _MAXCOLSDBSECTOR    9


int _Init_dbread(void);
int _dbread_table_tableschema_sector(void);
int _dbread_table_tableschema_dev(void);
int _dbread_table_muni(void);
int _dbread_table_devices(void); 
int _dbread_bulk(void);
//stDb_T_devices *_Stfind_Eqid(uint8_t *peqid, uint8_t eqlen);
//stDb_T_sector *_Stfind_muni(uint32_t mid);
uint8_t *_Findtargetfolder(uint8_t *peqid, uint8_t eqlen);
int8_t _CheckEq(uint8_t *peqid, uint8_t eqlen);
int8_t _CheckHubId(uint8_t *peqid, uint8_t eqlen);









#endif