-- LTServer DB Ver 1.1

-- Tabla para identificar versión de tablas
CREATE TABLE db_version (
    id SERIAL PRIMARY KEY,
    version CHAR(3) NOT NULL
);
INSERT INTO db_version (version) VALUES ('1.1');

-- Tabla de sector, actua de puente entre una municipalidad y una carpeta 
-- /path/a/carpeta/de/municipio/{year} para que en tiempo de ejecución se reemplace como /path/a/carpeta/de/municipio/2023 
CREATE TABLE public.sector (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	cid int2 NOT NULL,		-- cid = Country ID (54 = ARG)
	pid int2 NOT NULL,		-- province id 
	sector_id int4 NOT NULL,	-- sector id (código único numérico) 
	sector_name varchar(30) NOT NULL,
	folder_name varchar(30) NOT NULL,
	is_public_sector bool NOT NULL,
	is_geopos bool NOT NULL,
	map_file varchar(32) NOT NULL,
	CONSTRAINT "PK_sector" PRIMARY KEY (id)
);

-- tabla de dispositivos
-- tiene una fk a sector para identificar a que municipio o sector privado corresponde el dispositivo
CREATE TABLE public.devices (
	idx int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	eqid char(17) NOT NULL,  	-- Dirección de red (Formato string-hexa 12:34:56:78:9A:BC)
	linkid char(17) NOT NULL,  	-- Dirección del master (solo si is_linked = true), (Formato string-hexa 12:34:56:78:9A:BC)
	hubid char(17) NOT NULL, 	-- ID de la unidad central repetidora (Formato string-hexa 12:34:56:78:9A:BC)
	_uid char(20) NOT NULL,  	-- ID/Nombre local del dispositivo
	date_time timestamptz NOT NULL DEFAULT now(),
	devtype int2 NOT NULL,  	-- Enum del tipo de dispositivo (0-63) Tipo Luminaria, (64-127) Tipo de SIT, (128-255) Sistema de infracciones.
	serial_number varchar(32) NOT NULL,
	_name varchar(32) NOT NULL,
	model varchar(16) NOT NULL,
	address varchar(20) NOT NULL,
	address_number varchar(10) NOT NULL,
	intersection varchar(32) NOT NULL,
	zipcode varchar(16) NOT NULL,
	mapposx int NOT NULL,
	mapposy int NOT NULL,
	geo_latitude float NOT NULL,
	geo_longitude float NOT NULL,
	description varchar(32) NULL,
	sector_id int4 NOT NULL,	-- Sector id de la tabla "sector" al que corresponde el dispositivo
	map_loc char(32) NOT NULL,	-- Localidad / Ciudad
	map_pag int2 NOT NULL,		-- Página dentro del mapa 
	is_enabled bool NOT NULL,
	is_linked bool NOT NULL,
	devconfig int NOT NULL,  	-- Configuración para el dispositivo, (bitcode)
	CONSTRAINT "PK_devices" PRIMARY KEY (idx,eqid)
);
CREATE INDEX "IX_devices_sector_id" ON public.devices USING btree (sector_id);

-- tabla de último estado de dispositivos
CREATE TABLE public.state (
	eqid char(17) NOT NULL,  	-- Dirección de red (Formato string-hexa 12:34:56:78:9A:BC)
	linkid char(17) NOT NULL,  	-- Dirección del master (solo si is_linked = true), (Formato string-hexa 12:34:56:78:9A:BC)
	hubid char(17) NOT NULL, 	-- ID de la unidad central repetidora (Formato string-hexa 12:34:56:78:9A:BC)
	_uid char(20) NOT NULL,  	-- ID/Nombre local del dispositivo
	date_time timestamptz NOT NULL DEFAULT now(),
	devtype int2 NOT NULL,  	-- Enum del tipo de dispositivo (0-63) Tipo Luminaria, (64-127) Tipo de SIT, (128-255) Sistema de infracciones.
	mapposx int NOT NULL,
	mapposy int NOT NULL,
	geo_latitude float NOT NULL,
	geo_longitude float NOT NULL,
	sector_id int4 NOT NULL,	-- Sector id de la tabla "sector" al que corresponde el dispositivo
	map_loc char(32) NOT NULL,	-- Localidad / Ciudad
	map_pag int2 NOT NULL,		-- Página dentro del mapa 
	errstate int NOT NULL,		-- Estado de Error (<> 0 = Error)
	devstate int NOT NULL,  	-- Estado del dispositivo, (bitcode)
	updatecnt int4 NOT NULL,	-- Contador de actualización de estado
	CONSTRAINT "PK_state" PRIMARY KEY (eqid)
);

-- tabla de eventos de dispositivos
CREATE TABLE public.events (
	idx int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	_uid varchar(20) NOT NULL,  	-- ID/Nombre local del dispositivo
	eqid char(17) NOT NULL,  	-- Dirección de red (Formato string-hexa 12:34:56:78:9A:BC)
	date_time timestamptz NOT NULL DEFAULT now(),
	devstate int NOT NULL,	  	-- Estado del dispositivo, (bitcode)
	sector_id int4 NOT NULL,	-- Sector id de la tabla "sector" al que corresponde el dispositivo
	map_loc char(32) NOT NULL,	-- Localidad / Ciudad
	eventnr int NOT NULL		-- Código de evento
);

-- public.devices foreign keys
ALTER TABLE public.devices ADD CONSTRAINT "FK_devices_sector_id" FOREIGN KEY (sector_id) REFERENCES public.sector(id) ON DELETE CASCADE;

-- Inserta primer indice con valores de test para sector
INSERT INTO sector ("id","cid","pid", "sector_id", "sector_name", "folder_name", "is_public_sector", "is_geopos", "map_file")
VALUES (0,11, 12, 0,'sector_test', '/altiva/sector0', TRUE, FALSE,'/map_sector0');
	
-- Inserta primer indice con valores de test para devices
INSERT INTO devices ("idx", "eqid", "linkid", "hubid", "_uid", "devtype", "serial_number", "_name", "model", "address", "address_number", "intersection", "zipcode",
		     "mapposx", "mapposy", "geo_latitude", "geo_longitude", "description", "sector_id", "map_loc", "map_pag", "is_enabled", "is_linked", "devconfig") 
VALUES (0, '00:12:34:56:78:9A', '00:00:00:00:00:00','00:12:34:56:78:00', 'LP0001', 1,'serial001','Luminaria Simple', 'Luminar Tech', 'Av.Congreso', '1250','Av.Congreso y Justo','CP1560A', 
	200, 300, 1.2, 3.4, 'Luminaria de prueba',0,'Villa Ballester',2,TRUE,FALSE,65535); 

-- Inserta un segundo indice con valores de test para devices
INSERT INTO devices ("idx", "eqid", "linkid", "hubid", "_uid", "devtype", "serial_number", "_name", "model", "address", "address_number", "intersection", "zipcode",
		     "mapposx", "mapposy", "geo_latitude", "geo_longitude", "description", "sector_id", "map_loc", "map_pag", "is_enabled", "is_linked", "devconfig") 
VALUES (0, '00:22:33:56:78:9A', '00:00:00:00:00:00','00:12:34:56:78:00', 'LP0002', 1,'serial123','Luminaria Simple', 'Luminar Tech', 'Av.Congreso', '5550','Av.Congreso y Justo','CP1560A', 
	230, 320, 2.2, 2.4, 'Luminaria de prueba',0,'Villa Ballester',2,TRUE,FALSE,65535); 

-- Inserta primer estado con valores de test para devices
INSERT INTO state ("eqid", "linkid", "hubid", "_uid", "devtype", "mapposx", "mapposy", "geo_latitude", "geo_longitude", "sector_id", "map_loc", "map_pag", "errstate", "devstate", "updatecnt") 
VALUES ('00:12:34:56:78:9A', '00:00:00:00:00:00','00:12:34:56:78:00', 'LP0001', 1 ,200,300, 1.2, 3.4,0, 'Villa Ballester',5,1,256,0); 
	
-- Inserta un segundo estado con valores de test para devices
INSERT INTO state ("eqid", "linkid", "hubid", "_uid", "devtype", "mapposx", "mapposy", "geo_latitude", "geo_longitude", "sector_id", "map_loc", "map_pag", "errstate", "devstate", "updatecnt") 
VALUES ('00:22:33:56:78:9A', '00:00:00:00:00:00','00:12:34:56:78:00', 'LP0002', 1, 300, 350, 2.2, 2.4,0, 'Villa Ballester',5,0,256,0); 

-- Inserta un tercer estado con valores de test para devices
INSERT INTO state ("eqid", "linkid", "hubid", "_uid", "devtype", "mapposx", "mapposy", "geo_latitude", "geo_longitude", "sector_id", "map_loc", "map_pag", "errstate", "devstate", "updatecnt") 
VALUES ('00:22:33:56:78:9B', '00:00:00:00:00:00','00:12:34:56:78:00', 'LP0003', 1, 330, 310, 2.2, 2.4,0, 'Villa Ballester',7,0,256,0); 

-- Insertar eventos simulados
INSERT INTO public.events (_uid, eqid, date_time, devstate, sector_id, map_loc, eventnr) VALUES
  ('LP-0001', 'AA:BB:CC:DD:EE:01', now(), 0b00000001, 0, 'Villa Ballester', 101),
  ('LP-0002', 'AA:BB:CC:DD:EE:02', now(), 0b00000010, 0, 'Villa Ballester', 102),
  ('LP-0003', 'AA:BB:CC:DD:EE:03', now(), 0b00000100, 0, 'Villa Ballester', 103),
  ('LP-0004', 'AA:BB:CC:DD:EE:01', now(), 0b00000011, 0, 'Villa Ballester', 104),
  ('LP-0005', 'AA:BB:CC:DD:EE:02', now(), 0b00000101, 0, 'Villa Ballester', 105);




